name: Test-Truffle

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        id: trufflehog
        uses: trufflesecurity/trufflehog@main
        continue-on-error: true
        with:
          path: ./
          base: ${{ github.event.before }}
          head: ${{ github.sha }}
          extra_args: --debug
          version: latest

      - name: Send email if secret found
        if: steps.trufflehog.outcome == 'failure'
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "🚨 TruffleHog Secret Leak Detected in ${{ github.repository }}"
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.SMTP_USERNAME }}
          body: |
            Repository: ${{ github.repository }}
            Commit/PR: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}

            TruffleHog found a potential secret. 
            Please review commit and rotate impacted key.
